# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1

mod_version=1.5.11

jei_version=19.25.0.323

create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67

forgegradle_version = 6.0.6
mixingradle_version = 0.7-SNAPSHOT
mixin_version = 0.8.5
librarian_version = 1.+

cc_tweaked_enable = true
cc_tweaked_minecraft_version = 1.21.1
cc_tweaked_version = 1.115.1

mekanism_enable = false
mekanism_version = 1.21.1-10.7.15.81

ie_enabled = false
ie_version = 1.21.1-12.4.2-194

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.21.1]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.219
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.1.219,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

## Mod Properties
mod_id=createaddition
# The human-readable display name for the mod.
mod_name=Create Crafts & Additions
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT License, Copyright 2025 MRH0
# The mod version. See https://semver.org/
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.mrh0.createaddition
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=MRH0

